### ISSUE TITLE
[BUG REPORT] Version Not Updated in Latest Release

### ISSUE THREAD

**Issue by Klastic** [mage-docker/xmage-beta-docker#5]
**Description:**  
The docker image, which was expected to reflect updates as of August 16th, still shows the previous version. Upon investigating the GitHub Actions used for updating, it appears that the action responsible for the version has been disabled due to inactivity.

**Steps to Reproduce:**  
1. Go to the repository.
2. Navigate to the 'Actions' tab to review the status of the Update XMage Version action.

**Expected Behavior:**  
The version number should be updated to reflect the changes made in the release on August 16th.

**Actual Behavior:**  
The version number remains unchanged, and the Update XMage Version action intended to update it is disabled.

![image](https://github.com/user-attachments/assets/e36b31b4-f480-4c8d-bc09-35c7d8428f6d)

**Comment by DanceMore** [comment]
I am also here seeking a fresh build of XMage Server (Bloomburrow 🌲🎉  )

Docker Hub says:
> goesta/xmage-beta
> •Updated 3 months ago

`xmage.today` says:
> Latest update: 2024-08-16 15:45 UTC (6 days ago)

I tried a few times locally to build from source or from custom `bundle.zip` that I compiled fresh, but it feels like XMage client / server are very sensitive to version differences and I couldn't get anything to run that wasn't Official Builds :(

**Comment by Klastic** [comment]
I went ahead and forked this repo, got a build running, and am able to connect. I did this as a temp fix until the action is turned back on. The image name is `klastic/xmage-beta` for those wanting to use it. 

@DanceMore tagging you so you see this.

Happy gamming!

**Comment by goesta** [comment]
Hey Thanks for reporting this. Sorry for the inconvenience the newest release should now be available.
